# Source: https://github.com/redhat-scholars/argocd-tutorial/blob/master/documentation/modules/ROOT/examples/bgd-app/bgd-app.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-bgd-yaml
  namespace: app-bgd-yaml
spec:
  destination:
    namespace: bgd-yaml
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/devttao/argoproj'
    path: argocd/demos/service/bgd-yaml
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
